### ISSUE TITLE
The plugin generated 708 characters of unexpected output during activation.

### ISSUE THREAD

**Issue by snyggapa** [mdsimpson/contact-form-7-to-database-extension#10]
"The plugin generated 708 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin." received upon activation

installed  2.10.32 and got this warning. anything to be concerned about? I had to delete the original wordpress.org installed version first

also do you have any comments on PHP7 compatibility?

Thanks

Steve

**Comment by mdsimpson** [comment]
That is probably not be an issue. If the plugin seems to be working, then you can ignore that. 

[PHP7 Compatibility](https://cfdbplugin.com/?p=1544)
