### ISSUE TITLE
Saved Form Data only Shows Submitted Dates

### ISSUE THREAD

**Issue by lgrrealag** [mdsimpson/contact-form-7-to-database-extension#11]
For some reason when we go to check the data all we get is the submitted date, instead of the form data. I have attached a screenshot. We recently were moved to a PHP 7 server. The data appears to all be in the database but for some reason it is not displaying or exporting. We have the latest version (Version 2.10.32) installed. The data is coming from a Contact Form 7 form.

![screenshot 4](https://cloud.githubusercontent.com/assets/15734860/24122996/851fa1ea-0d83-11e7-937b-8cad6e59da19.png)

Any help or ideas of what might be happening would be appreciated.

Thanks,

**Comment by mdsimpson** [comment]
Any chance you have a test server that I could log into and poke around? Email me at info@cfdbplugin.com if so.

**Comment by lgrrealag** [comment]
I could give you access to our test server, but it works perfectly on the test server, but not production. Same software, same versions etc, but on production we get the above. I tried removing the plugin and the data and reinstalling. No luck.

Had a few minutes and installed Query Monitor. I get this error showing up when I try to load results:

SELECT DISTINCT `field_name` FROM `wp_cf7dbplugin_submits` WHERE `form_name` = 'Contest 2017' ORDER BY field_order	

Expression #1 of ORDER BY clause is not in SELECT list, references column 'DBNAME.wp_cf7dbplugin_submits.field_order' which is not in SELECT list; this is incompatible with DISTINCT

Any ideas? I'll see what I can dig up.

Thanks

**Comment by lgrrealag** [comment]
I have made some progress. This is related to the production server using HyperDB to read from more than one DB server. That is the only difference between the development server and the live server. Thanks for your time and a great plugin.
