### ISSUE TITLE
Switching from 2.10.29 to 2.10.32

### ISSUE THREAD

**Issue by adondeirhoy** [mdsimpson/contact-form-7-to-database-extension#13]
I skipped, because of the change to GitHub the previous updates, I already uploaded the Github updater, but need to move from my old version to the new version on http://adondeirhoy.com

Went via ftp changed the name of the old folder and uploaded the neew version since I did not know if all my data would be lost if I just deactivated/deleted the previous version and install the new one.

Now I get a 503 service unavailable when trying to get the contact form DB. I still have not deleted the old folder in case i need some file.

Please advice

**Comment by mdsimpson** [comment]
The data is not lost on uninstall/reinstall (unless you set the CFDB Option to make it do that). I think having that renamed directory is causing your 503.

**Comment by adondeirhoy** [comment]
I deleted the previous version, installed the new one and now it will not let me activate, when I go to settings I get Sorry, you are not allowed to access this page.

**Comment by mdsimpson** [comment]
The plugin installs as directory wp-content/plugins/contact-form-7-to-database-extension/
If you renamed that directory, delete what you renamed. If you FTP'ed another copy, delete it. WP tries to activate everything under "plugins", so having 2 copies of the same thing (even with diff directory names) is a problem. 

 I don't trust FTPing stuff into WordPress. That might be also be problem. I recommend installing the plugin through the WP Dashboard Plugins page where you can upload the .zip file to install it.
