### ISSUE TITLE
Share the plugin on packagist.org

### ISSUE THREAD

**Issue by dnaber-de** [mdsimpson/contact-form-7-to-database-extension#24]
:+1: for the composer.json
Would you mind to submit your plugin as package on https://packagist.org ? It's not much more than sign in to packagist.org via your github account and submitting the repository URL. Finally you can add a Github service integration (in the repository settings) to notify packagist on any update.

**Comment by gnowland** [comment]
Seconded

**Comment by mdsimpson** [comment]
Done.

**Comment by gnowland** [comment]
It looks like 2.10.35 is not available on packagist, have you set up the service hook in
[https://github.com/mdsimpson/contact-form-7-to-database-extension/settings/installations](https://github.com/mdsimpson/contact-form-7-to-database-extension/settings/installations)?

From packagist:

> Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Service Hooks". Pick "Packagist" in the list, and add your API token (from your profile: [https://packagist.org/profile/](https://packagist.org/profile/)), plus your Packagist username if it is not the same as on GitHub. Check the "Active" box and submit the form.
