### ISSUE TITLE
Compabilty with PHP 7.0

### ISSUE THREAD

**Issue by persoderman** [mdsimpson/contact-form-7-to-database-extension#26]
Hi,

When checking against PHP 7.0 we get these errors:

FILE:/wp-content/plugins/contact-form-7-to-database-extension/CFDBWpdbUnbufferedResultIterator.php
---------------------------------------------------------------------------------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
---------------------------------------------------------------------------------------------------------------------------------------------
  72 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
  74 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
  97 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 100 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 122 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 124 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
---------------------------------------------------------------------------------------------------------------------------------------------

FILE: /wp-content/plugins/contact-form-7-to-database-extension/CFDBQueryResultIterator.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 13 ERRORS AFFECTING 13 LINES
------------------------------------------------------------------------------------------------------------------------------------
  47 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
  59 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
  85 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
  87 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 114 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 121 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 122 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 132 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 136 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 138 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 146 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 150 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 152 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
------------------------------------------------------------------------------------------------------------------------------------

FILE:/wp-content/plugins/contact-form-7-to-database-extension/phpunit/WP_Mock_Functions.php
--------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------
 48 | WARNING | Function name "__" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
--------------------------------------------------------------------------------------------------------------------------------------

**Comment by persoderman** [comment]
As we want to move to PHP 7.0 asap and we love this plugin can the above issues be fixed asap?

Per

**Comment by mdsimpson** [comment]
See: https://cfdbplugin.com/?p=1544

**Comment by persoderman** [comment]
Thanks for clarifying this!

Per
