### ISSUE TITLE
Add support for afragen/github-updater

### ISSUE THREAD

**Issue by egifford** [mdsimpson/contact-form-7-to-database-extension#3]
Hi,

Great plugin.  I've been using it for a few years with success.

Could you add support for https://github.com/afragen/github-updater?

It is a plugin that allows WordPress to pull plugin updates directly from GitHub.  This will be really useful since your code base is now located there.

To make it work, just 2 new lines are needed in the plugin header.

I've got a pull request ready to go.

Thanks!

**Comment by egifford** [comment]
Thanks for merging!

**Comment by mdsimpson** [comment]
Thanks for the suggestion!
