### ISSUE TITLE
Why can this plugin no longer be found in official WP repository?

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [mdsimpson/contact-form-7-to-database-extension#32]
Is there a reason?
Please make it available in wp svn again :)
So we can update via WP update page!

Thanks!

**Comment by kimipooh** [comment]
The plugin developer said the reason on the support forum of wordpress.org.
- https://wordpress.org/support/topic/is-cfdb-gone/#post-8732785

Of course, I hope to come back again, but I think that it's most important that updates continue.

**Comment by s-a-s-k-i-a** [comment]
True. and I just found out that @mdsimpson 's  plugin should be compatible with WordPress Github Updater Plugin (https://github.com/afragen/github-updater), which allows updating via WordPress Plugin page.
Thanks Michael!

Best
Saskia
