### ISSUE TITLE
Tag on commit with composer.json

### ISSUE THREAD

**Issue by mkuhles** [mdsimpson/contact-form-7-to-database-extension#5]
hi msimpson,

may you add a tag on the commit https://github.com/mdsimpson/contact-form-7-to-database-extension/commit/1abe2a095f16847dc774c1ef34b858e76029c245, please. So I can reference your plugin in my composer file by a tag and haven't to use the precise commit.

Thanks.
mkuhles

**Comment by mdsimpson** [comment]
The latest release tag is "2.10.31"

**Comment by mkuhles** [comment]
Thanks :)
