### ISSUE TITLE
Problems with new Version 2.10.35 (FIXED with 2.10.36 !)

### ISSUE THREAD

**Issue by jesusptas** [mdsimpson/contact-form-7-to-database-extension#58]
I just installed version 2.10.35 right now and when I select a form in the dropdown list to show or edit the fields it says "No results were found". This happens with many old forms, but not with all of them.
I am sure the data is there because the shortcodes work. I can see the data of the forms through Shortocodes but not from the CFDB module as always.
Thank you

**Comment by jesusptas** [comment]
![no-data](https://user-images.githubusercontent.com/37593223/38571268-56de848e-3cf0-11e8-9013-8f9864c52a95.jpg)

**Comment by jesusptas** [comment]
OK, I have been investigating. The problem is when a form has a simbol in its name. Things like "-" (dash), "ª", etc

**Comment by jesusptas** [comment]
![no-data](https://user-images.githubusercontent.com/37593223/38573239-b4e37044-3cf5-11e8-8df6-8c8119c199f9.jpg)

**Comment by mdsimpson** [comment]
I fixed in 2.10.36. Please verify.

**Comment by jesusptas** [comment]
Verified and confirmed too. Thank you Michael Simpson, you are great!
