### ISSUE TITLE
Nothing on Wordpress ?

### ISSUE THREAD

**Issue by TomasHurtz** [mdsimpson/contact-form-7-to-database-extension#6]
I like your plugin but why no plugin on Wordpress repository where we can get update?

Thank you for your work.

**Comment by dunepebbler** [comment]
I agree. We use this plugin on 100+ websites and it would be a pain to update now, or to install the github auto-update plugin as suggested at your website. 
What is the reason behind switching to GitHub?

**Comment by TomasHurtz** [comment]
I found more info - You can read all about it here: https://wordpress.org/support/topic/is-cfdb-gone/

Seems a disagreement with a WP moderator! Not to mention any names, but I have seen how condescending they can be.  I think @mdsimpson has every right to be annoyed/upset with them.

Why the WP team can't be more supportive?  Probably just a personality clash !  

Hope you get the respect you deserve @mdsimpson and get the help you need to get it back up there.

All the best

**Comment by dunepebbler** [comment]
Thank you for the update @TomasHurtz.
I completely understand @mdsimpson 

So if I'm correct, after reading the linked discussion. The WP.org version of CFDB we use on our sites still contains the vulnerability that needs to be patched by manually updating them with this GitHub version?

**Comment by mdsimpson** [comment]
Correct

**Comment by afragen** [comment]
Just and FYI, if you're going to use [GitHub Updater](https://github.com/afragen/github-updater) make sure you download the `master` branch.

**Comment by tariquesani** [comment]
Can we have a release from the current master?

**Comment by afragen** [comment]
@mdsimpson once you start tagging releases GitHub Updater will only use the current tag for download. If your version number is greater than your current tag your users will see an update notice and then update to the current tag. An endless cycle may result.

**Comment by mdsimpson** [comment]
I created a new release off master: https://github.com/mdsimpson/contact-form-7-to-database-extension/releases/

**Comment by afragen** [comment]
@mdsimpson there might be a problem with sorting order of the tags as there is one with a `v2.x.x` which is a lower version but might be sorted higher. You might need to delete that tag. It's a combination of `version_compare` and array sorting. Best to stick with pure numbers for versions. 

I don't know if this is the issue. I haven't checked.

**Comment by mdsimpson** [comment]
Will do, thanks for the advice.

**Comment by TomasHurtz** [comment]
Will it get back on WordPress anytime soon @mdsimpson  ?

**Comment by mdsimpson** [comment]
No. I'm not working on it.

**Comment by Ciantic** [comment]
Great plugin, but by removing it from Wordpress.org it basically goes unused in future, cause it's not common to install Github updater just for this.
