### ISSUE TITLE
How to find latest version number?

### ISSUE THREAD

**Issue by cagross** [mdsimpson/contact-form-7-to-database-extension#72]
How do I determine the latest version number of the plugin?  I want to confirm that my installed version is up to date.

Also, in the future, where should I post similar support questions? Should I do so here, or is there another forum/contact form I should use?

Thanks.

**Comment by mdsimpson** [comment]
Latest release: https://github.com/mdsimpson/contact-form-7-to-database-extension/releases

You can also install GitHub updated to keep it up to date: GitHub https://github.com/afragen/github-updater/releases

**Comment by cagross** [comment]
OK thanks for that.

>> You can also install GitHub updated to keep it up to date: GitHub https://github.com/afragen/github-updater/releases

I actually already have that installed.  I'm conducting this manual test to confirm that GitHub Updated is doing its job.  It is :-)

We can consider this resolved.  But for the future, if I have similar support questions, can/should I post them here?

**Comment by mdsimpson** [comment]
Yes, but I’m not always quick to respond

**Comment by cagross** [comment]
Great thanks.  I'll call this issue closed then.
