### ISSUE TITLE
Form exclusion

### ISSUE THREAD

**Issue by mayatekxp** [mdsimpson/contact-form-7-to-database-extension#8]
Hi ,
i'm having a problem with your plugin.
I'd like to DONT SAVE data from some forms in my website.
I made the proper configuration in the plugin option page->Do not save forms in DB named (comma-separated list, no spaces) 
Data of the form excluded are not recorded in the db table 'cf7dbplugin_submits' as configured but the problem is due the fact the pluging still store data (submit_time) in db table 'cf7dbplugin_st'.
Please can you help me sort this out?
greets

P.s.:
You made a great job with this very usefull plugin.

**Comment by mdsimpson** [comment]
This is nothing to worry about. The cf7dbplugin_st is used to make sure there are no duplicate submit times generated. They are temporary values in that table are intermittently deleted.

**Comment by mayatekxp** [comment]
I'm not worried. I just need to exclude the plugin records data from forms excluded.
Can you help me on this please?
